import type { Metadata } from "next";
import { Limelight, Frank_Ruhl_Libre, Pontano_Sans, Playfair_Display } from 'next/font/google'
import "./globals.css";
import AuthProvider from "@/components/providers/AuthProvider";
import { Toaster } from "sonner";
import SmoothScrolling from "@/components/providers/LennisProvider";




const limeLight = Limelight({ subsets: ['latin'], weight: '400', variable: '--font-limeLight' })
const FrankRuhlLibre = Frank_Ruhl_Libre ({subsets: ['latin'], weight: '400', variable: '--font-FrankRuhlLibre' })
const PlayfairDisplay = Playfair_Display({ subsets: ['latin'], weight: '400', variable: '--font-PlayfairDisplay'})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`${FrankRuhlLibre.variable} ${PlayfairDisplay.variable} ${limeLight.variable}`}>
      <body>
        <AuthProvider>
          <Toaster richColors toastOptions={{ classNames: { title: 'text-lg' } }} />
          <SmoothScrolling>
          {children}
          </SmoothScrolling>
        </AuthProvider>
      </body>
    </html>
  );
}
